### ISSUE TITLE
GitHub Education Benefits for Faculty

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-farhansj#12]
Hi @farhansj! Thank you for completing all of the assignments of the Campus Advisor training. However, it looks like you have not yet applied for GitHub Education benefits for faculty. If you are currently employed as faculty:

1. Apply for GitHub Education benefits for faculty at https://education.github.com/discount_requests/new.
2. After you are approved for faculty benefits, reapply for the Campus Advisor program. The application link is in the Campus Advisor offer in the GitHub Teacher Toolboox.
<img width="300" alt="GitHub Campus Advisors application in the GitHub Teacher Toolbox" src="https://user-images.githubusercontent.com/2359538/80523551-df4edd80-8953-11ea-8b22-10dfc98065d2.png">
3. In the application, link to this training repository so that we can review the work you've already done.  

  
However, if you are currently a student, you may be interested in the [GitHub Campus Experts](https://education.github.com/students/experts) program instead.

**Comment by farhansj** [comment]
Hi Arelia,

I already applied since 31st March 2020, but still pending for approval until now. Perhaps if you could help to have a look at my application and approve it if you have the authority to do so.

![image](https://user-images.githubusercontent.com/7088099/80536885-ac4d2e00-89d5-11ea-8a79-2c54e6e5900d.png)

Regards

**Comment by arelia** [comment]
Hi @farhansj, it looks like you were approved on April 29. Congratulations! You'll receive an email soon to schedule an interview for the Campus Advisors program.

**Comment by farhansj** [comment]
Hi @arelia , I am so sorry that I missed the interview slot. It’s quite challenging to wake up at 4am despite I had locked my alarm clock. Anyway, I am available now for the interview if you still have time.
